[build]
  command = "#"
  publish = "dist"
  functions = "lambda"

[build.processing]
  skip_processing = false

[build.processing.css]
  minify = true

[build.processing.js]
  minify = true

[build.processing.images]
  compress = true

[[redirects]]
  from = "https://placekeanu.netlify.com/*"
  to = "https://placekeanu.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/"
  to = "/"
  status = 200
  force = true

[[redirects]]
  from = "/favicon.ico"
  to = "/static/favicon.ico"
  status = 200
  force = true

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/keanus"
  to = "/keanus"
  status = 200
  force = true

[[redirects]]
  from = "/error"
  to = "/error"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/generator/:splat"
  status = 200
  force = true